#!/usr/bin/env bash
# This script transfers a file from the client to the server.
# → Arg[0] = Filename (not used)
# → Arg[1] = PATH_TO_FILE
# → Arg[2] = IP
# → Arg[3] = USERNAME
# → Arg[4] = PATH_TO_SSH_KEY


if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"

fi
