#!/usr/bin/env bash
# This script redirects to another page
# nginx listens to port 80
# Returns a page containing "Holberton School" when querying at its root

sudo apt-get update

sudo apt-get -y install nginx

#For the firewall
sudo ufw allow 'Nginx HTTP'

echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html

sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;" /etc/nginx/sites-available/default

service nginx restart
