#!/usr/bin/env bash
# This script redirects to another page
# nginx listens to port 80
# Returns a page with the error 404

sudo apt-get update

sudo apt-get -y install nginx

#For the firewall
sudo ufw allow 'Nginx HTTP'

echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html

sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.\com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default


echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
