#!/usr/bin/env bash
# This script repairs the connection to the port 0:80 for nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx stop
