#!/usr/bin/env bash
# This script creates an infinite loop
counter=0
echo "$(pgrep -f 100-process_and_pid_file)" > /var/run/holbertonscript.pid
while [ $counter -lt 10 ]
do
    echo "To infinity and beyond"
    trap "echo I hate the kill command" SIGTERM
    trap "rm /var/run/holbertonscript.pid" SIGTERM
    trap "echo Y U no love me?!" SIGINT
    trap "rm /var/run/holbertonscript.pid" SIGQUIT
    sleep 2
done
