#!/usr/bin/env bash
# This script displays Hi when the counter reaches 9
counter=0
while [ $counter -lt 10 ]
do
    if [ $counter == 9 ]
    then
	echo "Hi"
    fi
    echo "Holberton School"
    counter=$((counter + 1))
done
