#!/usr/bin/env bash
# This script uses the statement if to modify the output
counter=1
while [ $counter -le 10 ]
do
    if [ $counter == 4 ]
    then
	echo "bad luck"
    elif [ $counter == 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    counter=$((counter + 1))
done
