#!/usr/bin/env bash
# This script is displaying a clock from 00:00 to 12:59
hours=0
while [ $hours -le 12 ]
do
    echo "Hour: $hours"
    minutes=1
    while [ $minutes -lt 60 ]
    do
	echo "$minutes"
	((minutes++))
    done
    ((hours++))

done
