#!/usr/bin/env bash
# Run as user nginx
chmod 664 /etc/nginx/nginx.conf
sed -ie 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -ie 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx /etc/init.d/nginx start
